
import static com.microsoft.sqlserver.jdbc.StringUtils.isNumeric;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RidwanSaputra
 */
public class menukeluar extends javax.swing.JFrame {
    
    ClassMenuKeluar keluar = new ClassMenuKeluar();
    
    database koneksi = new database();
    
    
    
    public menukeluar() {
        initComponents();
        btkeluar.setEnabled(false);
        btedit.setEnabled(false);
        btbayar.setEnabled(false);
        printstruk.setEnabled(false);
        kodetransaksi.requestFocus();
        nopolisi2.setEnabled(false);
        jeniskendaraan2.setEnabled(false);
        jammasuk2.setEnabled(false);
        jamkeluar.setEnabled(false);
        txtlamaparkir.setEnabled(false);
        txtuangmasuk.setEnabled(false);
        datakeluar.setText("-");
        txtpotongan.setText("-");
        setLocationRelativeTo(null);
        tanggal2.setText(keluar.getTanggal());
        setJam();
        Connection con =null;
        Statement stm =null;
        ResultSet Rs =null;
    }
     public final void setJam(){
    ActionListener taskPerformer = new ActionListener() {

                @Override
    public void actionPerformed(ActionEvent evt) {
    String nol_jam = "", nol_menit = "",nol_detik = "";

    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();

    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";

    String jam = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);

    jam2.setText(jam+":"+menit+":"+detik+"");
    }
    };
    new Timer(1000, taskPerformer).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tanggal2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jam2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nopolisi2 = new javax.swing.JTextField();
        cari2 = new javax.swing.JButton();
        jeniskendaraan2 = new javax.swing.JTextField();
        jammasuk2 = new javax.swing.JTextField();
        jamkeluar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlamaparkir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        totalbiaya = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JLabel();
        txtkembalian1 = new javax.swing.JLabel();
        btkeluar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtuangmasuk = new javax.swing.JTextField();
        btbayar = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        datakeluar = new javax.swing.JLabel();
        txtpotongan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kodetransaksi = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        printstruk = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kembali2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Tanggal : ");

        tanggal2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tanggal2.setText("00/00/00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Jam : ");

        jam2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jam2.setText("00:00:00");

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NO POLISI");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("JAM MASUK");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("JAM KELUAR");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("JENIS KENDARAAN");

        nopolisi2.setBackground(new java.awt.Color(204, 204, 204));
        nopolisi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nopolisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolisi2ActionPerformed(evt);
            }
        });
        nopolisi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nopolisi2KeyPressed(evt);
            }
        });

        cari2.setBackground(new java.awt.Color(255, 51, 0));
        cari2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cari2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        cari2.setText("CARI");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });
        cari2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari2KeyPressed(evt);
            }
        });

        jeniskendaraan2.setBackground(new java.awt.Color(204, 204, 204));
        jeniskendaraan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jammasuk2.setBackground(new java.awt.Color(204, 204, 204));
        jammasuk2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jamkeluar.setBackground(new java.awt.Color(204, 204, 204));
        jamkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jamkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamkeluarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("LAMA PARKIR");

        txtlamaparkir.setBackground(new java.awt.Color(204, 204, 204));
        txtlamaparkir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtlamaparkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlamaparkirActionPerformed(evt);
            }
        });
        txtlamaparkir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlamaparkirKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlamaparkirKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jam");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total Biaya : Rp.");

        totalbiaya.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalbiaya.setText("0");

        a.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a.setText("Kembalian : Rp.");

        txtkembalian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtkembalian.setText("0");

        txtkembalian1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtkembalian1.setText("===================");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkembalian1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(totalbiaya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtkembalian1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(txtkembalian))
                .addGap(31, 31, 31))
        );

        btkeluar.setBackground(new java.awt.Color(255, 51, 0));
        btkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btkeluar.setText("KELUAR");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        btkeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btkeluarKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("UANG MASUK");

        txtuangmasuk.setBackground(new java.awt.Color(204, 204, 204));
        txtuangmasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtuangmasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuangmasukKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuangmasukKeyReleased(evt);
            }
        });

        btbayar.setBackground(new java.awt.Color(255, 51, 0));
        btbayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btbayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/payment.png"))); // NOI18N
        btbayar.setText("BAYAR");
        btbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbayarActionPerformed(evt);
            }
        });

        btedit.setBackground(new java.awt.Color(255, 51, 0));
        btedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/riwayat.png"))); // NOI18N
        btedit.setText("EDIT");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datakeluar.setBackground(new java.awt.Color(0, 0, 204));
        datakeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datakeluar.setForeground(new java.awt.Color(0, 0, 204));
        datakeluar.setText("data dengan no polisi 111111 telah dikeluarkan");

        txtpotongan.setBackground(new java.awt.Color(0, 0, 204));
        txtpotongan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpotongan.setForeground(new java.awt.Color(0, 0, 204));
        txtpotongan.setText("==> POTONGAN HARGA 2 JAM PARKIR <==");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpotongan)
                    .addComponent(datakeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(datakeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(txtpotongan)
                .addGap(19, 19, 19))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("KODE TRANSAKSI");

        kodetransaksi.setBackground(new java.awt.Color(204, 204, 204));
        kodetransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kodetransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodetransaksiActionPerformed(evt);
            }
        });
        kodetransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodetransaksiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodetransaksiKeyReleased(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 51, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });

        printstruk.setBackground(new java.awt.Color(255, 51, 0));
        printstruk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printstruk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pr.png"))); // NOI18N
        printstruk.setText("PRINT");
        printstruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printstrukActionPerformed(evt);
            }
        });
        printstruk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printstrukKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtuangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jeniskendaraan2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nopolisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(121, 121, 121))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(kodetransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cari2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jammasuk2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtlamaparkir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jamkeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(printstruk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodetransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cari2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nopolisi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jeniskendaraan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jammasuk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btkeluar))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlamaparkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printstruk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbayar)
                    .addComponent(txtuangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENU KELUAR PARKIRAN");

        kembali2.setBackground(new java.awt.Color(255, 51, 0));
        kembali2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembali2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/backkk.png"))); // NOI18N
        kembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(237, 237, 237)
                .addComponent(kembali2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembali2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jam2))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tanggal2)
                    .addComponent(jLabel4)
                    .addComponent(jam2))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        if(kodetransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan Kode Transaksi","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                kodetransaksi.requestFocus();
        }else{
       koneksi.kodetransaksi = kodetransaksi.getText();
            koneksi.carikeluar();
            nopolisi2.setText(koneksi.no_pol);
            jeniskendaraan2.setText(koneksi.jeniskendaraan);
            jammasuk2.setText(koneksi.jammasuk);
            if(nopolisi2.getText().equals("")){
                btkeluar.setEnabled(false);
                kodetransaksi.requestFocus();
            }else{
                kodetransaksi.setEnabled(false);
                cari2.setEnabled(false);
                btkeluar.setEnabled(true);
            btkeluar.requestFocus();
            }
        }
    }//GEN-LAST:event_cari2ActionPerformed

    private void jamkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamkeluarActionPerformed

    private void kembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali2ActionPerformed
        // TODO add your handling code here:
        new menu().show();
           this.dispose();
    }//GEN-LAST:event_kembali2ActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
       btkeluar.setEnabled(false);
        if(keluar.getUsername().equals("ADMIN")){
        btedit.setEnabled(true);
        }else{
           btedit.setEnabled(false); 
        }
        btbayar.setEnabled(true);    
        keluar.setJam(jam2.getText());
        jamkeluar.setText(keluar.getJam());
        koneksi.nopolisi = nopolisi2.getText();
        jamkeluar.setText(jam2.getText());
        String jami = jammasuk2.getText();
        String[] jamin = jami.split(":");
        String Jamin = jamin[0];
        int jamin1 = Integer.parseInt(Jamin);
        
        String jamkeluar1 = jamkeluar.getText();
        String[] jamout = jamkeluar1.split(":");
        String Jamout = jamout[0];
        int Jamout1 = Integer.parseInt(Jamout);
        
        datakeluar.setText("Data dengan no polisi " +nopolisi2.getText()+ " telah keluar !");
        keluar.setJamMasuk(jamin1);
        keluar.setJamKeluar1(Jamout1);
        keluar.setJenisKendaraan(jeniskendaraan2.getText());
        keluar.setHargaKendaraan();
        txtlamaparkir.setText(Integer.toString(keluar.getLamaParkir()));
        keluar.setEditLama(Integer.parseInt(txtlamaparkir.getText()));
        keluar.getTotalBayar();
        txtlamaparkir.setText(Integer.toString(keluar.getLamaParkir()));
        totalbiaya.setText(Integer.toString(keluar.getTotalBayar()));
        txtuangmasuk.setEnabled(true);
        txtuangmasuk.requestFocus();
                       
        
    }//GEN-LAST:event_btkeluarActionPerformed

    private void btbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbayarActionPerformed
        // TODO add your handling code here:
          if(txtuangmasuk.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Masukan Uang Masuk","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                txtuangmasuk.requestFocus();
            }else if (!isNumeric(txtuangmasuk.getText())){
            JOptionPane.showMessageDialog(null, "Masukan angka!","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtuangmasuk.setText("");
            }else{
            keluar.setTotalBayarSemua(Integer.parseInt(totalbiaya.getText()));
        keluar.setUangMasuk(Integer.parseInt(txtuangmasuk.getText()));
        txtkembalian.setText(Integer.toString(keluar.getKembalian()));
        nopolisi2.setEnabled(false);
        txtuangmasuk.setEnabled(false);
        txtlamaparkir.setEnabled(false);
        btedit.setEnabled(false);
        btbayar.setEnabled(false);
        printstruk.setEnabled(true);
        if(Integer.parseInt(txtlamaparkir.getText())>10){
            txtpotongan.setText("==> POTONGAN HARGA 2 JAM PARKIR <==");
        }
        reset.requestFocus();
        keluar.getAddLaporan();
        
        datakeluar.setText("Transaksi Berhasil .. !");
        
        koneksi.no_pol = nopolisi2.getText();
        koneksi.jenis = jeniskendaraan2.getText();
        koneksi.jam_out = jamkeluar.getText();
        koneksi.jam_in = jammasuk2.getText();
        koneksi.lama = txtlamaparkir.getText();
        koneksi.biaya = totalbiaya.getText();
        koneksi.datamenukeluar();
        }
    }//GEN-LAST:event_btbayarActionPerformed

//System.err.println("Exception: "+e.getMessage());
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kodetransaksi.setText("");
        btkeluar.setEnabled(false);
        btedit.setEnabled(false);
        btbayar.setEnabled(false);  
        nopolisi2.setEnabled(false);
        cari2.setEnabled(true);
        kodetransaksi.setEnabled(true);
        printstruk.setEnabled(false);
        kodetransaksi.requestFocus();
        nopolisi2.setText("");
        jeniskendaraan2.setText("");
        jammasuk2.setText("");
        jamkeluar.setText("");
        txtlamaparkir.setText("");
        totalbiaya.setText("0");
        txtuangmasuk.setText("");
        txtkembalian.setText("0");
        datakeluar.setText("-");
        txtpotongan.setText("-");
    }//GEN-LAST:event_resetActionPerformed

    private void txtlamaparkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlamaparkirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlamaparkirActionPerformed

    private void nopolisi2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nopolisi2KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nopolisi2KeyPressed

    private void cari2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari2KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cari2KeyPressed

    private void btkeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btkeluarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        btkeluar.setEnabled(false);
        if(keluar.getUsername().equals("ADMIN")){
        btedit.setEnabled(true);
        }else{
           btedit.setEnabled(false); 
        }
        btbayar.setEnabled(true);    
        keluar.setJam(jam2.getText());
        jamkeluar.setText(keluar.getJam());
        koneksi.nopolisi = nopolisi2.getText();
        jamkeluar.setText(jam2.getText());
        String jami = jammasuk2.getText();
        String[] jamin = jami.split(":");
        String Jamin = jamin[0];
        int jamin1 = Integer.parseInt(Jamin);
        
        String jamkeluar1 = jamkeluar.getText();
        String[] jamout = jamkeluar1.split(":");
        String Jamout = jamout[0];
        int Jamout1 = Integer.parseInt(Jamout);
        
        datakeluar.setText("Data dengan no polisi " +nopolisi2.getText()+ " telah keluar !");
        keluar.setJamMasuk(jamin1);
        keluar.setJamKeluar1(Jamout1);
        keluar.setJenisKendaraan(jeniskendaraan2.getText());
        keluar.setHargaKendaraan();
        txtlamaparkir.setText(Integer.toString(keluar.getLamaParkir()));
        keluar.setEditLama(Integer.parseInt(txtlamaparkir.getText()));
        keluar.getTotalBayar();
        txtlamaparkir.setText(Integer.toString(keluar.getLamaParkir()));
        totalbiaya.setText(Integer.toString(keluar.getTotalBayar()));
        txtuangmasuk.setEnabled(true);
        txtuangmasuk.requestFocus();
                       
        }
    }//GEN-LAST:event_btkeluarKeyPressed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        txtlamaparkir.setEnabled(true);
        txtuangmasuk.setEnabled(false);
        txtlamaparkir.requestFocus();
    }//GEN-LAST:event_bteditActionPerformed

    private void nopolisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolisi2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nopolisi2ActionPerformed

    private void txtlamaparkirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlamaparkirKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtlamaparkir.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Masukan Lama Parkir","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                txtlamaparkir.requestFocus();
            }
            else if (!isNumeric(txtlamaparkir.getText())){
            JOptionPane.showMessageDialog(null, "Masukan angka!","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtlamaparkir.setText("");
            }else{
        keluar.setJenisKendaraan( jeniskendaraan2.getText());
        keluar.getHargaKendaraan();
        keluar.setEditLama( Integer.parseInt(txtlamaparkir.getText()));
        totalbiaya.setText(Integer.toString(keluar.getTotalBayarEdit()));
        txtuangmasuk.setEnabled(true);
        txtlamaparkir.setEnabled(false);
        txtuangmasuk.requestFocus();
        
        }}
    }//GEN-LAST:event_txtlamaparkirKeyPressed

    private void txtuangmasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangmasukKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtuangmasuk.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Masukan Uang Masuk","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                txtuangmasuk.requestFocus();
            }else if (!isNumeric(txtuangmasuk.getText())){
            JOptionPane.showMessageDialog(null, "Masukan angka!","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtuangmasuk.setText("");
            }else{
            
            keluar.setTotalBayarSemua(Integer.parseInt(totalbiaya.getText()));
        keluar.setUangMasuk(Integer.parseInt(txtuangmasuk.getText()));
        txtkembalian.setText(Integer.toString(keluar.getKembalian()));
        nopolisi2.setEnabled(false);
        txtuangmasuk.setEnabled(false);
        txtlamaparkir.setEnabled(false);
        btedit.setEnabled(false);
        btbayar.setEnabled(false);
        printstruk.setEnabled(true);
        if(Integer.parseInt(txtlamaparkir.getText())>10){
            txtpotongan.setText("==> POTONGAN HARGA 2 JAM PARKIR <==");
        }
        reset.requestFocus();
        keluar.getAddLaporan();
        
        datakeluar.setText("Transaksi Berhasil .. !");
        
        koneksi.no_pol = nopolisi2.getText();
        koneksi.jenis = jeniskendaraan2.getText();
        koneksi.jam_out = jamkeluar.getText();
        koneksi.jam_in = jammasuk2.getText();
        koneksi.lama = txtlamaparkir.getText();
        koneksi.biaya = totalbiaya.getText();
        koneksi.datamenukeluar();
        }}
    }//GEN-LAST:event_txtuangmasukKeyPressed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
        // TODO add your handling code here:
       btkeluar.setEnabled(false);
        btedit.setEnabled(false);
        btbayar.setEnabled(false);  
        nopolisi2.setEnabled(false);
        cari2.setEnabled(true);
        kodetransaksi.setEnabled(true);
        printstruk.setEnabled(false);
        kodetransaksi.requestFocus();
        nopolisi2.setText("");
        kodetransaksi.setText("");
        jeniskendaraan2.setText("");
        jammasuk2.setText("");
        jamkeluar.setText("");
        txtlamaparkir.setText("");
        totalbiaya.setText("0");
        txtuangmasuk.setText("");
        txtkembalian.setText("0");
        datakeluar.setText("-");
        txtpotongan.setText("-");
    }//GEN-LAST:event_resetKeyPressed

    private void kodetransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodetransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodetransaksiActionPerformed

    private void kodetransaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodetransaksiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            if(kodetransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan Kode Transaksi","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                kodetransaksi.requestFocus();
        }else{
            koneksi.kodetransaksi = kodetransaksi.getText();
            koneksi.carikeluar();
            nopolisi2.setText(koneksi.no_pol);
            jeniskendaraan2.setText(koneksi.jeniskendaraan);
            jammasuk2.setText(koneksi.jammasuk);
            if(nopolisi2.getText().equals("")){
                btkeluar.setEnabled(false);
                kodetransaksi.requestFocus();
            }else{
                btkeluar.setEnabled(true);
                kodetransaksi.setEnabled(false);
                cari2.setEnabled(false);
            btkeluar.requestFocus();
            }
        }}
    }//GEN-LAST:event_kodetransaksiKeyPressed

    private void printstrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printstrukActionPerformed
        // TODO add your handling code here:
        keluar.setKodeTransaksi(kodetransaksi.getText());
        keluar.setNoPolisi(nopolisi2.getText());
        keluar.setJenisKendaraan(jeniskendaraan2.getText());
        keluar.setHargaKendaraan();
        keluar.setLp(Integer.parseInt(txtlamaparkir.getText()));
        keluar.setTb(totalbiaya.getText());
        new printstruk().show();
    }//GEN-LAST:event_printstrukActionPerformed

    private void printstrukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printstrukKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_printstrukKeyPressed

    private void kodetransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodetransaksiKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_kodetransaksiKeyReleased

    private void txtlamaparkirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlamaparkirKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtlamaparkirKeyReleased

    private void txtuangmasukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangmasukKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtuangmasukKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton btbayar;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton cari2;
    private javax.swing.JLabel datakeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jam2;
    private javax.swing.JTextField jamkeluar;
    private javax.swing.JTextField jammasuk2;
    private javax.swing.JTextField jeniskendaraan2;
    private javax.swing.JButton kembali2;
    private javax.swing.JTextField kodetransaksi;
    private javax.swing.JTextField nopolisi2;
    private javax.swing.JButton printstruk;
    private javax.swing.JButton reset;
    private javax.swing.JLabel tanggal2;
    private javax.swing.JLabel totalbiaya;
    private javax.swing.JLabel txtkembalian;
    private javax.swing.JLabel txtkembalian1;
    private javax.swing.JTextField txtlamaparkir;
    private javax.swing.JLabel txtpotongan;
    private javax.swing.JTextField txtuangmasuk;
    // End of variables declaration//GEN-END:variables
}
