

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RidwanSaputra
 */
public class menumasuk extends javax.swing.JFrame {

    /**
     * Creates new form menumasuk
     */
    ClassMenuMasuk masuk = new ClassMenuMasuk();
    database koneksi = new database();
    

    
    public menumasuk() {
        initComponents();
        btprint.setEnabled(false);
        txtpetugas.setText(masuk.getUsername());
        notif.setText("");
        txtnopolisi.setEnabled(false);
        txtjammasuk.setEnabled(false);
        txthargaperjam.setEnabled(false);
        textarea1.setEnabled(false);
        txtkode.setEnabled(false);
        btsimpan.setEnabled(false);
        setLocationRelativeTo(null);
        
        
        
        
        setJam();
        Connection con =null;
        Statement stm =null;
        ResultSet Rs =null;
        }
    
    void hapus(){
        txtjeniskendaraan.setSelectedItem("PILIH JENIS KENDARAAN");
        txtnopolisi.setText("");
        txthargaperjam.setText("");
        txtjammasuk.setText("");
        textarea1.setText("");
        textarea1.setEnabled(false);
        txtnopolisi.setEnabled(false);
        notif1.setText("*Input data");
        txtkode.setText("");
        txtnopolisi.setEnabled(false);
        }
    
    public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {

        @Override
    public void actionPerformed(ActionEvent evt) {
        String nol_jam = "", nol_menit = "",nol_detik = "";

        java.util.Date dateTime = new java.util.Date();
        int nilai_jam = dateTime.getHours();
        int nilai_menit = dateTime.getMinutes();
        int nilai_detik = dateTime.getSeconds();

        if(nilai_jam <= 9) nol_jam= "0";
        if(nilai_menit <= 9) nol_menit= "0";
        if(nilai_detik <= 9) nol_detik= "0";

        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);

        txtjam.setText(jam+":"+menit+":"+detik+"");
        }
        };
        new Timer(1000, taskPerformer).start();
        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtjeniskendaraan = new javax.swing.JComboBox<>();
        txtnopolisi = new javax.swing.JTextField();
        txtjammasuk = new javax.swing.JTextField();
        txthargaperjam = new javax.swing.JTextField();
        notif = new javax.swing.JLabel();
        btsimpan = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btprint = new javax.swing.JButton();
        notif1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtjam = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpetugas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NO POLISI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("JENIS KENDARAAN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("HARGA PER JAM");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("JAM MASUK");

        txtjeniskendaraan.setBackground(new java.awt.Color(204, 204, 204));
        txtjeniskendaraan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjeniskendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JENIS KENDARAAN", "Motor", "Mobil", "Bus" }));
        txtjeniskendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjeniskendaraanActionPerformed(evt);
            }
        });

        txtnopolisi.setBackground(new java.awt.Color(204, 204, 204));
        txtnopolisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnopolisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnopolisiActionPerformed(evt);
            }
        });
        txtnopolisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnopolisiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnopolisiKeyReleased(evt);
            }
        });

        txtjammasuk.setBackground(new java.awt.Color(204, 204, 204));
        txtjammasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjammasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjammasukActionPerformed(evt);
            }
        });

        txthargaperjam.setBackground(new java.awt.Color(204, 204, 204));
        txthargaperjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        notif.setBackground(new java.awt.Color(0, 0, 255));
        notif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notif.setForeground(new java.awt.Color(0, 51, 255));

        btsimpan.setBackground(new java.awt.Color(255, 51, 0));
        btsimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add barang.png"))); // NOI18N
        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 51, 0));
        bthapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        bthapus.setText("RESET");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        bthapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bthapusKeyPressed(evt);
            }
        });

        btprint.setBackground(new java.awt.Color(255, 51, 0));
        btprint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pr.png"))); // NOI18N
        btprint.setText("PRINT");
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        notif1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notif1.setForeground(new java.awt.Color(0, 0, 204));
        notif1.setText("*Input data");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("KODE TRANSAKSI");

        txtkode.setBackground(new java.awt.Color(204, 204, 204));
        txtkode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(notif1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btsimpan)
                                .addGap(12, 12, 12)
                                .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtjeniskendaraan, javax.swing.GroupLayout.Alignment.LEADING, 0, 343, Short.MAX_VALUE)
                            .addComponent(txtnopolisi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthargaperjam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjammasuk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(notif)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtkode, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtjeniskendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtnopolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthargaperjam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtjammasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notif)
                .addGap(18, 18, 18)
                .addComponent(notif1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        textarea1.setColumns(20);
        textarea1.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        textarea1.setRows(5);
        jScrollPane2.setViewportView(textarea1);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("TANGGAL :");

        txttanggal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttanggal.setText("txttanggal");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("JAM :");

        txtjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtjam.setText("txtjam");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("NAMA PETUGAS :");

        txtpetugas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtpetugas.setText("txtpetugas");

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORM MENU MASUK KENDARAAN");

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/backkk.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttanggal)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtjam))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpetugas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpetugas)
                    .addComponent(txtjam)
                    .addComponent(jLabel7)
                    .addComponent(txttanggal)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new menu().show();
           this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        try {
            // TODO add your handling code here:
            textarea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(menumasuk.class.getName()).log(Level.SEVERE, null, ex);
        }
    

    }//GEN-LAST:event_btprintActionPerformed

    private void bthapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bthapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            hapus();
            btprint.setEnabled(false);
            txtjeniskendaraan.setEnabled(true);
            txtnopolisi.setEnabled(false);
            btsimpan.setEnabled(false);
            
            txtjeniskendaraan.requestFocus();
        }
    }//GEN-LAST:event_bthapusKeyPressed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        hapus();
            btprint.setEnabled(false);
            txtjeniskendaraan.setEnabled(true);
            txtnopolisi.setEnabled(false);
            btsimpan.setEnabled(false);
            
            txtjeniskendaraan.requestFocus();
    }//GEN-LAST:event_bthapusActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        if(txtnopolisi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan No Polisi","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            txtnopolisi.requestFocus();
        }else{
        masuk.setUsername(txtpetugas.getText());
        masuk.setNoPolisi(txtnopolisi.getText());
        masuk.setJam(txtjam.getText());
        txtkode.setText("P"+masuk.getTanggalBulan()+Integer.toString(masuk.getKode()));
        masuk.setKodeTransaksi(txtkode.getText());
        txtjammasuk.setText(masuk.getJam());
        textarea1.setEnabled(true);
        masuk.setStruk();
        
        
        textarea1.append(masuk.getStruk());
        notif1.setText("*Data telah tersimpan*");
        txttanggal.setText(masuk.getTanggal());
        
        
        btprint.setEnabled(true);
        txtjeniskendaraan.setEnabled(false);
        txtnopolisi.setEnabled(false);
        btsimpan.setEnabled(false);
        koneksi.kodetransaksi = txtkode.getText();
        koneksi.biaya = txthargaperjam.getText();
        koneksi.no_pol = txtnopolisi.getText();
        koneksi.jenis = (String)txtjeniskendaraan.getSelectedItem();
        koneksi.jam_in = txtjammasuk.getText();
        koneksi.datamenumasuk();
        bthapus.requestFocus();
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void txtjammasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjammasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjammasukActionPerformed

    private void txtnopolisiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnopolisiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtnopolisi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan No Polisi","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            txtnopolisi.requestFocus();
        }else{
        masuk.setUsername(txtpetugas.getText());
        masuk.setNoPolisi(txtnopolisi.getText());
        masuk.setJam(txtjam.getText());
        txtkode.setText("P"+masuk.getTanggalBulan()+Integer.toString(masuk.getKode()));
        masuk.setKodeTransaksi(txtkode.getText());
        txtjammasuk.setText(masuk.getJam());
        textarea1.setEnabled(true);
        masuk.setStruk();
        
        
        textarea1.append(masuk.getStruk());
        notif1.setText("*Data telah tersimpan*");
        txttanggal.setText(masuk.getTanggal());
        
        
        btprint.setEnabled(true);
        txtjeniskendaraan.setEnabled(false);
        txtnopolisi.setEnabled(false);
        btsimpan.setEnabled(false);
        koneksi.kodetransaksi = txtkode.getText();
        koneksi.biaya = txthargaperjam.getText();
        koneksi.no_pol = txtnopolisi.getText();
        koneksi.jenis = (String)txtjeniskendaraan.getSelectedItem();
        koneksi.jam_in = txtjammasuk.getText();
        koneksi.datamenumasuk();
        bthapus.requestFocus();
        }}
    }//GEN-LAST:event_txtnopolisiKeyPressed

    private void txtnopolisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnopolisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopolisiActionPerformed

    private void txtjeniskendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjeniskendaraanActionPerformed
        // TODO add your handling code here:
        
        masuk.setJenisKendaraan((String) txtjeniskendaraan.getSelectedItem());
        masuk.getJenisKendaraan();
        masuk.setHargaKendaraan();
       txthargaperjam.setText(Integer.toString(masuk.getHargaKendaraan()));
        //txthargaperjam.setText(Integer.toString(masuk.getHargaKendaraan()));
        if (masuk.getJenisKendaraan().equals("Motor")||(masuk.getJenisKendaraan().equals("Mobil"))||(masuk.getJenisKendaraan().equals("Bus"))){
            txtnopolisi.setEnabled(true);
            btsimpan.setEnabled(true);
            txtnopolisi.requestFocus();
        }else{
            txtnopolisi.setEnabled(false);
            btsimpan.setEnabled(false);
            
            
        }
    }//GEN-LAST:event_txtjeniskendaraanActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void txtnopolisiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnopolisiKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnopolisiKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btprint;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel notif;
    private javax.swing.JLabel notif1;
    private javax.swing.JTextArea textarea1;
    private javax.swing.JTextField txthargaperjam;
    private javax.swing.JLabel txtjam;
    private javax.swing.JTextField txtjammasuk;
    private javax.swing.JComboBox<String> txtjeniskendaraan;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnopolisi;
    private javax.swing.JLabel txtpetugas;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
